import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/session.dart';
import '../models/attendance_record.dart';

class PdfService {
  static Future<Uint8List> generateAttendancePDF({
    required AttendanceSession session,
    required List<AttendanceRecord> records,
    Map<String, int>? previousAttendance,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) => [
          // Header
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.center,
              children: [
                pw.Text(
                  'Attendance Report',
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // Session Info
          pw.Text(
            'Course: ${session.courseName}',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.Text(
            'Session Date: ${session.startTime.toString().substring(0, 16)}',
            style: const pw.TextStyle(fontSize: 14),
          ),
          pw.Text(
            'Duration Required: ${session.requiredConnectionMinutes} min',
            style: const pw.TextStyle(fontSize: 14),
          ),
          pw.SizedBox(height: 20),

          // Attendance Table with proper columns
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
            columnWidths: {
              0: const pw.FlexColumnWidth(2.2),   // Student Name
              1: const pw.FlexColumnWidth(1.4),   // Matricule
              2: const pw.FlexColumnWidth(2.4),   // Email
              3: const pw.FlexColumnWidth(1.0),   // Status
              4: const pw.FlexColumnWidth(1.2),   // Joined At
              5: const pw.FlexColumnWidth(1.0),   // Duration
            },
            children: [
              // Table Header
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.blue900),
                children: [
                  _buildHeaderCell('Student Name'),
                  _buildHeaderCell('Matricule'),
                  _buildHeaderCell('Email'),
                  _buildHeaderCell('Status'),
                  _buildHeaderCell('Joined At'),
                  _buildHeaderCell('Duration'),
                ],
              ),
              // Data Rows
              ...records.map((record) => pw.TableRow(
                children: [
                  _buildDataCell(record.studentName),
                  _buildDataCell(record.matricule),
                  _buildDataCell(record.email ?? 'N/A'),
                  _buildStatusCell(record.isVerified),
                  _buildDataCell(
                    '${record.joinedAt.hour.toString().padLeft(2, '0')}:${record.joinedAt.minute.toString().padLeft(2, '0')}',
                  ),
                  _buildDataCell('${record.connectionDurationMinutes} min'),
                ],
              )),
            ],
          ),

          pw.SizedBox(height: 20),

          // Summary Section
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
              children: [
                _buildSummaryItem('Total Students', records.length.toString()),
                _buildSummaryItem(
                  'Verified',
                  records.where((r) => r.isVerified).length.toString(),
                ),
                _buildSummaryItem(
                  'Pending',
                  records.where((r) => !r.isVerified).length.toString(),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 30),

          // Footer
          pw.Container(
            alignment: pw.Alignment.center,
            child: pw.Text(
              'Generated by Hotspot Attendance System',
              style: pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey,
                fontStyle: pw.FontStyle.italic,
              ),
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeaderCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.white,
          fontSize: 10,
        ),
      ),
    );
  }

  static pw.Widget _buildDataCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 9),
      ),
    );
  }

  static pw.Widget _buildStatusCell(bool isVerified) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Container(
        padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 3),
        decoration: pw.BoxDecoration(
          color: isVerified ? PdfColors.green100 : PdfColors.orange100,
          borderRadius: pw.BorderRadius.circular(4),
        ),
        child: pw.Text(
          isVerified ? 'Verified' : 'Pending',
          style: pw.TextStyle(
            fontSize: 9,
            color: isVerified ? PdfColors.green800 : PdfColors.orange800,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ),
    );
  }

  static pw.Widget _buildSummaryItem(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 18,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blue900,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
      ],
    );
  }
}

