// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2OSiPR96nYTtALVt8oNPdAMyvfPPvsic',
    appId: '1:484804376077:web:b8c73a58f3e43212920744',
    messagingSenderId: '484804376077',
    projectId: 'attendance-app-2526',
    authDomain: 'attendance-app-2526.firebaseapp.com',
    storageBucket: 'attendance-app-2526.firebasestorage.app',
    measurementId: 'G-7MYTESC2JB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAMjJY-eBNZmtX9P-ojRhH1IaXKKejekY',
    appId: '1:484804376077:ios:e08bdc8a3f2b9ef8920744',
    messagingSenderId: '484804376077',
    projectId: 'attendance-app-2526',
    storageBucket: 'attendance-app-2526.firebasestorage.app',
    iosClientId: '484804376077-6hdmmcfc08iv4p9qh8tailrc7nbr6t7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAMjJY-eBNZmtX9P-ojRhH1IaXKKejekY',
    appId: '1:484804376077:ios:e08bdc8a3f2b9ef8920744',
    messagingSenderId: '484804376077',
    projectId: 'attendance-app-2526',
    storageBucket: 'attendance-app-2526.firebasestorage.app',
    iosClientId: '484804376077-6hdmmcfc08iv4p9qh8tailrc7nbr6t7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2OSiPR96nYTtALVt8oNPdAMyvfPPvsic',
    appId: '1:484804376077:web:0d570c23216e702e920744',
    messagingSenderId: '484804376077',
    projectId: 'attendance-app-2526',
    authDomain: 'attendance-app-2526.firebaseapp.com',
    storageBucket: 'attendance-app-2526.firebasestorage.app',
    measurementId: 'G-70GJT3RR10',
  );
}
